# Hệ số Gain P (Proportional) và D (Derivative) cho các khớp của chân (Right Leg)
r_hip_yaw_p_gain : 0.0  # Hệ số Gain P cho khớp R_HIP_YAW
r_hip_yaw_d_gain : 0.0  # Hệ số Gain D cho khớp R_HIP_YAW

r_hip_roll_p_gain : 0.0  # Hệ số Gain P cho khớp R_HIP_ROLL
r_hip_roll_d_gain : 0.0  # Hệ số Gain D cho khớp R_HIP_ROLL

r_hip_pitch_p_gain : 0.0  # Hệ số Gain P cho khớp R_HIP_PITCH
r_hip_pitch_d_gain : 0.0  # Hệ số Gain D cho khớp R_HIP_PITCH

r_knee_p_gain  : 0.0  # Hệ số Gain P cho khớp R_KNEE
r_knee_d_gain  : 0.0  # Hệ số Gain D cho khớp R_KNEE

r_ank_pitch_p_gain  : 0.0  # Hệ số Gain P cho khớp R_ANKLE_PITCH
r_ank_pitch_d_gain  : 0.0  # Hệ số Gain D cho khớp R_ANKLE_PITCH

r_ank_roll_p_gain  : 0.0  # Hệ số Gain P cho khớp R_ANKLE_ROLL
r_ank_roll_d_gain  : 0.0  # Hệ số Gain D cho khớp R_ANKLE_ROLL


# Hệ số Gain P (Proportional) và D (Derivative) cho các khớp của chân (Left Leg)
l_hip_yaw_p_gain : 0.0  # Hệ số Gain P cho khớp L_HIP_YAW
l_hip_yaw_d_gain : 0.0  # Hệ số Gain D cho khớp L_HIP_YAW

l_hip_roll_p_gain : 0.0  # Hệ số Gain P cho khớp L_HIP_ROLL
l_hip_roll_d_gain : 0.0  # Hệ số Gain D cho khớp L_HIP_ROLL

l_hip_pitch_p_gain : 0.0  # Hệ số Gain P cho khớp L_HIP_PITCH
l_hip_pitch_d_gain : 0.0  # Hệ số Gain D cho khớp L_HIP_PITCH

l_knee_p_gain  : 0.0  # Hệ số Gain P cho khớp L_KNEE
l_knee_d_gain  : 0.0  # Hệ số Gain D cho khớp L_KNEE

l_ank_pitch_p_gain  : 0.0  # Hệ số Gain P cho khớp L_ANKLE_PITCH
l_ank_pitch_d_gain  : 0.0  # Hệ số Gain D cho khớp L_ANKLE_PITCH

l_ank_roll_p_gain  : 0.0  # Hệ số Gain P cho khớp L_ANKLE_ROLL
l_ank_roll_d_gain  : 0.0  # Hệ số Gain D cho khớp L_ANKLE_ROLL
